<!-- Estilo Padrão -->
<link rel="stylesheet" type="text/css" href="assets/css/login.css">
<main>
    <form>
        <div>
            <img src="assets/image/icone.png" alt="Logo da Página"><span>#FocusManager</span>
        </div>
        <fieldset>
            <legend>Faça seu Login:</legend>
            <label for="email">Email:</label>
            <input type="email" placeholder="fulano@email.com" title="Digite seu email" name="email" required>
            <label for="password">Senha:</label>
            <input type="password" title="Digite sua senha" name="password" required>
        </fieldset>
        <fieldset>
            <button>Entrar</button>
            <br><br>
            <small>Esqueceu a senha? então </small><button type="button">Recuperar minha senha</button>
        </fieldset>
    </form>
    <div id="cloud"></div>
</main>