<form>
    <fieldset>
        <legend>Faça seu Login:</legend>
        <label for="email">Email:</label>
        <input type="email" placeholder="fulano@email.com" title="Digite seu email" name="email">
        <label for="password">Senha:</label>
        <input type="password" title="Digite sua senha" name="password">
    </fieldset>
    <fieldset>
        <legend>Acesso:</legend>
        <button>Entrar</button>
        <small>Ou</small>
        <button type="button">Registrar</button>
        <small>Não tem uma conta? então</small><button type="button">Cadastre</button>
    </fieldset>
</form>